[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.25"

evm-version = "cancun"


remappings = [
    "@opensezppling/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
